/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteRouteImport } from './routes/collection/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as CollectionCardsRouteImport } from './routes/collection/cards'
import { Route as CollectionSealedRouteImport } from './routes/collection/sealed'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PricesIndexRouteImport } from './routes/prices/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsLocationsRouteImport } from './routes/settings/locations'
import { Route as SettingsPricesRouteImport } from './routes/settings/prices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRouteRoute = CollectionRouteRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const CollectionCardsRoute = CollectionCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const CollectionSealedRoute = CollectionSealedRouteImport.update({
  id: '/sealed',
  path: '/sealed',
  getParentRoute: () => CollectionRouteRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesIndexRoute = PricesIndexRouteImport.update({
  id: '/prices/',
  path: '/prices/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsLocationsRoute = SettingsLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPricesRoute = SettingsPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => SettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/collection/cards': typeof CollectionCardsRoute
  '/collection/sealed': typeof CollectionSealedRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/prices': typeof SettingsPricesRoute
  '/catalog/': typeof CatalogIndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection/cards': typeof CollectionCardsRoute
  '/collection/sealed': typeof CollectionSealedRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/prices': typeof SettingsPricesRoute
  '/catalog': typeof CatalogIndexRoute
  '/collection': typeof CollectionIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/prices': typeof PricesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/collection/cards': typeof CollectionCardsRoute
  '/collection/sealed': typeof CollectionSealedRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/locations': typeof SettingsLocationsRoute
  '/settings/prices': typeof SettingsPricesRoute
  '/catalog/': typeof CatalogIndexRoute
  '/collection/': typeof CollectionIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/prices/': typeof PricesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/settings'
    | '/collection/cards'
    | '/collection/sealed'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/locations'
    | '/settings/prices'
    | '/catalog/'
    | '/collection/'
    | '/portfolio/'
    | '/prices/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection/cards'
    | '/collection/sealed'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/locations'
    | '/settings/prices'
    | '/catalog'
    | '/collection'
    | '/portfolio'
    | '/prices'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/settings'
    | '/collection/cards'
    | '/collection/sealed'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/locations'
    | '/settings/prices'
    | '/catalog/'
    | '/collection/'
    | '/portfolio/'
    | '/prices/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRouteRoute: typeof CollectionRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  CatalogIndexRoute: typeof CatalogIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PricesIndexRoute: typeof PricesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/collection/cards': {
      id: '/collection/cards'
      path: '/cards'
      fullPath: '/collection/cards'
      preLoaderRoute: typeof CollectionCardsRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/collection/sealed': {
      id: '/collection/sealed'
      path: '/sealed'
      fullPath: '/collection/sealed'
      preLoaderRoute: typeof CollectionSealedRouteImport
      parentRoute: typeof CollectionRouteRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices/': {
      id: '/prices/'
      path: '/prices'
      fullPath: '/prices/'
      preLoaderRoute: typeof PricesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/locations': {
      id: '/settings/locations'
      path: '/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof SettingsLocationsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/prices': {
      id: '/settings/prices'
      path: '/prices'
      fullPath: '/settings/prices'
      preLoaderRoute: typeof SettingsPricesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface CollectionRouteRouteChildren {
  CollectionCardsRoute: typeof CollectionCardsRoute
  CollectionSealedRoute: typeof CollectionSealedRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const CollectionRouteRouteChildren: CollectionRouteRouteChildren = {
  CollectionCardsRoute: CollectionCardsRoute,
  CollectionSealedRoute: CollectionSealedRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

const CollectionRouteRouteWithChildren = CollectionRouteRoute._addFileChildren(
  CollectionRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsLocationsRoute: typeof SettingsLocationsRoute
  SettingsPricesRoute: typeof SettingsPricesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsLocationsRoute: SettingsLocationsRoute,
  SettingsPricesRoute: SettingsPricesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRouteRoute: CollectionRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  CatalogIndexRoute: CatalogIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PricesIndexRoute: PricesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
